version: "3.8"


services:

  # Following service is for local deployment
  wg-enhanced-local:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST="${hostname}"

      # Optional (see README.md for descriptions):
    #      - WEB_PORT=51821
    #      - PASSWORD=foobar123
    #      - WG_PORT=51820
    #      - WG_DEFAULT_DNS=1.1.1.1
    #      - WG_DEFAULT_MTU=1420
    #      - WG_DEFAULT_PERSISTENT_KEEPALIVE=0
    #      - WG_SUBNET=10.8.0.0/24
    #      - NETWORK_INTERFACE=eth0
    #      - WG_INTERFACE=wg0
    #      - WG_PATH=/etc/wireguard/
    #      - WG_PREAMBLE_EXPIRATON=30000
    #      - WG_PRE_UP=echo 'Hey, this is PreUp Script executed on this host';
    #      - WG_PRE_DOWN=echo 'Hey, this is PreDown Script executed on this host';
    #      - WG_POST_UP=echo 'Hey, this is PostUp Script executed on this host';
    #      - WG_POST_DOWN=echo 'Hey, this is PostDown Script executed on this host';
    #      - WG_DEFAULT_PRE_UP=echo 'Hey, this is the default PreUp Script for other peers';
    #      - WG_DEFAULT_PRE_DOWN=echo 'Hey, this is the default PreDown Script for other peers';
    #      - WG_DEFAULT_POST_UP=echo 'Hey, this is the default PostUp Script for other peers';
    #      - WG_DEFAULT_POST_DOWN=echo 'Hey, this is the default PostDown Script for other peers';

    build: .
    container_name: wg-enhanced-local
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  wg-enhanced-local-dev:
    extends: wg-enhanced-local
    container_name: wg-enhanced-local-dev
    command: npm run serve
    volumes:
      - ./src/:/app/
    # environment:
    #   - PASSWORD=p
